production: &production
  host: <%= ENV.fetch("REDIS_URL").split(":")[2].split("@")[1] if Rails.env.production? %>
  port: <%= ENV.fetch("REDIS_URL").split(":")[3] if Rails.env.production? %>
  password: <%= ENV.fetch("REDIS_URL").split(":")[2].split("@")[0] if Rails.env.production? %>
  timeout: 1

development: &development
  host: <%= ENV.fetch("REDIS_URL", "127.0.0.1") %>
  port: <%= ENV.fetch("REDIS_PORT", "6379") %>
  timeout: 1

test:
  <<: *development